//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int32_t pwnme(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x804a030

// ------------------------ Functions -------------------------

// Address range: 0x8048546 - 0x80485ad
int main(int argc, char ** argv) {
    // 0x8048546
    setvbuf(g1, NULL, 2, 0);
    puts("ret2win by ROP Emporium");
    puts("x86\n");
    pwnme();
    puts("\nExiting");
    return 0;
}

// Address range: 0x80485ad - 0x804862c
int32_t pwnme(void) {
    // 0x80485ad
    int32_t buf; // bp-44, 0x80485ad
    memset(&buf, 0, 32);
    puts("For my first trick, I will attempt to fit 56 bytes of user input into 32 bytes of stack buffer!");
    puts("What could possibly go wrong?");
    puts("You there, may I have your input please? And don't worry about null bytes, we're using read()!\n");
    printf("> ");
    read(0, &buf, 56);
    return puts("Thank you!");
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 2

